using System.Collections.Generic;
using Z6xToolBox.App.Content.Modules.Customization;
using Z6xToolBox.App.Content.Modules.Development;
using Z6xToolBox.App.Content.Modules.GoServices;
using Z6xToolBox.App.Content.Modules.Instructions;
using Z6xToolBox.App.Content.Modules.PreAdb;
using Z6xToolBox.App.Content.Modules.RustServices;
using Z6xToolBox.App.Framework.Models;

namespace Z6xToolBox.App.Content;

public static class ContentRegistry
{
    public static IReadOnlyList<ModuleDefinition> GetAllModules() =>
    [
        // 1-8 折腾经历与通道探索
        HdmiDisplayData.Create(),
        UsbApk1BypassData.Create(),
        LanSharingFlowData.Create(),
        AppCompatibilityData.Create(),
        SshHardwareAuditData.Create(),
        SshUninstallFailureData.Create(),
        DeveloperModeBlocksData.Create(),
        ForceAdbdActivationData.Create(),

        // 9-40 常用系统指令全解
        AdbCommandReferenceData.Create(),
        PmAmCommandReferenceData.Create(),
        PropertyCommandReferenceData.Create(),
        SystemDiagnosisReferenceData.Create(),
        CmdSvcContentReferenceData.Create(),
        StorageSecurityKernelReferenceData.Create(),
        ThermalMediaNetworkReferenceData.Create(),
        PowerNetworkInputCrashReferenceData.Create(),
        MediaBroadcastPartitionReferenceData.Create(),
        DrmDisplayUsbReferenceData.Create(),
        JobAlarmUserMonitorReferenceData.Create(),
        AudioAlsaSubsystemReferenceData.Create(),
        LmkMemoryForensicsReferenceData.Create(),
        SelinuxAuditReferenceData.Create(),
        OtaRecoveryReferenceData.Create(),
        NetworkProxyRoutingReferenceData.Create(),
        XgimiDebloatReferenceData.Create(),
        BluetoothRfkillReferenceData.Create(),
        InitDaemonIceSeaReferenceData.Create(),
        InputSensorsEventReferenceData.Create(),
        WifiSupplicantStateReferenceData.Create(),
        DisplayWindowDensityReferenceData.Create(),
        BatteryPowerArchitectureReferenceData.Create(),
        VendorPartitionCalibrationReferenceData.Create(),
        DmVerityFilesystemReferenceData.Create(),
        RebootWatchdogReferenceData.Create(),
        WirelessScreenCastReferenceData.Create(),
        LogcatBufferRotationReferenceData.Create(),
        ProcessSignalsKillReferenceData.Create(),
        SystemClockNtpReferenceData.Create(),
        KernelProcSysFsReferenceData.Create(),
        ShellEnvironmentPathReferenceData.Create(),

        // 深度定制（1 至 14 独立顺序）
        DebloatAdserviceData.Create(),
        DebloatMediaExtrasData.Create(),
        DebloatIotServicesData.Create(),
        DebloatWizardInstructionData.Create(),
        DebloatStreamRecommendData.Create(),
        ClashLocalProxyData.Create(),
        ActivityLauncherDirectData.Create(),
        AdbScreencapDiagnosticData.Create(),
        ProjectivyLauncherSetupData.Create(),
        TvAppMarketAlternativeData.Create(),
        StockHomeSkinDebloatData.Create(),
        OtaFirmwareBlockData.Create(),
        CompanionIotDebloatData.Create(),
        IncompatibleAppCleanData.Create(),
        HeadlessSystemPackagesData.Create(),
        InputMethodReplaceData.Create(),
        NativeScreenCastMiracastData.Create(),
        OneKeyBackupRestoreScriptData.Create(),

        // 开发环境（1 至 9）
        NativeExecutionArchitectureData.Create(),
        BusyboxEnvironmentData.Create(),
        GoCrossCompileDaemonData.Create(),
        SystemMetricsMonitorData.Create(),
        NativeDropbearSshServerData.Create(),
        ShellProfileEnvironmentData.Create(),
        StraceSyscallDebuggingData.Create(),
        TcpdumpNetworkPacketCaptureData.Create(),
        ProcessOomWatchdogPolicyData.Create(),

        // Go原生服务（1 至 60）
        WebDavFileHubServiceData.Create(),
        Aria2HeadlessDownloadNodeData.Create(),
        LocalDnsAdblockForwarderData.Create(),
        MultiPaneVideoStreamingArchitectureData.Create(),
        SubsonicMusicStreamingServerData.Create(),
        HomeAssistantDeviceBridgeData.Create(),
        NetworkKeepAliveStandbyData.Create(),
        GalleryHubPhotoServiceData.Create(),
        DeckSyncArchiveGatewayData.Create(),
        HardwareTelemetryWatchdogData.Create(),
        LocalClipboardTextRelayData.Create(),
        LiveProxyStreamingHubData.Create(),
        ComicEbookReaderServerData.Create(),
        LanSpeedLatencyProbeData.Create(),
        VirtualTouchpadKeyMacroData.Create(),
        DlnaMediaRendererData.Create(),
        WakeOnLanDeviceInspectorData.Create(),
        BigScreenFloatingNotificationData.Create(),
        ScreenOffWirelessAudioStreamerData.Create(),
        WebTerminalDirectAccessData.Create(),
        UserSpaceSmbFileShareData.Create(),
        MovieScraperNfoGeneratorData.Create(),
        LightweightMqttBrokerData.Create(),
        LanForwardingProxyNodeData.Create(),
        RssFeedMediaAggregatorData.Create(),
        S3CompatibleMinioLiteStorageData.Create(),
        UPnPPortMappingManagerData.Create(),
        PrometheusMetricsNodeExporterData.Create(),
        OAuth2LocalAuthProxyData.Create(),
        GitRepositoryLfsMirrorData.Create(),
        JsonRpcRemoteControlBridgeData.Create(),
        HttpLiveStreamingSegmenterData.Create(),
        ZeroTierMoonPlanetaryRelayData.Create(),
        TimedTaskWebhookDispatcherData.Create(),
        SftpServerStorageGatewayData.Create(),
        LanDnsDhcpServerData.Create(),
        DynamicDnsClientUpdaterData.Create(),
        HttpProxyAdBlockPacServerData.Create(),
        TorrentMetadataMagnetIndexerData.Create(),
        ScreenMiracastSignalingRelayData.Create(),
        MultiRoomAudioStreamSyncData.Create(),
        SubtitleAutoDownloaderData.Create(),
        LogAggregationLokiLiteData.Create(),
        SmartHomeMatterBridgeData.Create(),
        SpeedtestTrackerCollectorData.Create(),
        UdpBroadcastWOLRelayData.Create(),
        WebpThumbnailGeneratorData.Create(),
        M3uPlaylistAggregatorEditorData.Create(),
        LocalSpeedMeasurementIperf3GatewayData.Create(),
        AlistMultiCloudDriveMountData.Create(),
        TlsCertAutoRenewerData.Create(),
        BilibiliLiveDanmuStreamRecorderData.Create(),
        SsdpUpnpDeviceScannerData.Create(),
        MqttInfluxDbMetricsCollectorData.Create(),
        TailscaleSubnetRouterData.Create(),
        WebRtcSignalingScreenShareHubData.Create(),
        FileDeduplicationHardlinkOptimizerData.Create(),
        DynamicFormWebConfigUiData.Create(),
        EpgXmlTvCrawlerAggregatorData.Create(),
        UnifiedGoMonolithHubArchitectureData.Create(),

        // Rust原生服务（1 至 49）
        LowMemorySystemWatchdogData.Create(),
        EvdevInputEventRemapperData.Create(),
        JitterFreeAudioPcmMixerData.Create(),
        SimdFastFileChecksumData.Create(),
        UserSpaceWireGuardTunnelData.Create(),
        ZeroCopyMmapKvEngineData.Create(),
        BluetoothLowEnergyBridgeData.Create(),
        CrashBlackboxLogRecorderData.Create(),
        PortKnockSecurityDaemonData.Create(),
        DohDotEncryptedDnsProxyData.Create(),
        ZstdStreamCompressorData.Create(),
        LogSanitizerRotatorData.Create(),
        LowLatencyWebSocketEngineData.Create(),
        RustHardwareMetricsExporterData.Create(),
        UDiskHealthCheckInspectorData.Create(),
        TokenBucketBandwidthLimiterData.Create(),
        EmbeddedUltraLightWebDavData.Create(),
        HighFrequencyInputInjectorData.Create(),
        MicroProcessSupervisorData.Create(),
        ZeroCopyPacketSnifferData.Create(),
        LightweightMqttEdgeNodeData.Create(),
        ZeroCopyHttpStaticCacheData.Create(),
        UsbSerialHardwareBridgeData.Create(),
        UserSpaceTunPacketRouterData.Create(),
        LockFreeAudioCaptureProbeData.Create(),
        EpollHybridSocksHttpProxyData.Create(),
        EmbeddedFtsMediaIndexData.Create(),
        TimerWheelMicroCronData.Create(),
        ThermalThrottleMonitorData.Create(),
        LowLatencyUdpScreenCastingRelayData.Create(),
        InotifyFileEventSynchronizerData.Create(),
        RawFrameBufferScreenshotCaptureData.Create(),
        MemoryMappedConfigStoreData.Create(),
        HighPrecisionNetworkLatencyJitterProbeData.Create(),
        MicroMdnsServiceDiscoveryData.Create(),
        ZeroCopyDirectIoBenchmarkData.Create(),
        RawPtyTerminalMultiplexerData.Create(),
        EmbeddedLz4FrameTranscoderData.Create(),
        HdmiCecBusControllerData.Create(),
        RawAlsaHardwareMixerData.Create(),
        UsbHidDeviceEmulatorData.Create(),
        DnsConcurrencyRacerData.Create(),
        LowOverheadWebTerminalData.Create(),
        ZeroCopyRingBufferIpcData.Create(),
        BluetoothRawHciScannerData.Create(),
        UdpBroadcastScreenMirrorSignalingData.Create(),
        StaticBinaryP2PChunkDistributorData.Create(),
        LinuxCgroupResourceJailData.Create(),
        UnifiedRustCoreDaemonData.Create()
    ];
}
