# 审核结论表：(verdict, 去向, 实测与结论, 额外引用的原文说法 或 None)
# verdict: C=实测成立/可行, U=未验证/有未验证前提, D=不可行/关键说法不成立
G = {
1: ("C","hub·files（一期）","可行，纳入 hub 的 files 模块。静态 Go 程序能跑、8085 这类高位端口能绑定都已实测；/data 实测剩余 46G（原文说 47GB，接近）。U 盘实际在 /storage/<卷ID>/ 下，shell 可访问。","U 盘重新拔插后路径失效……服务启动参数建议直接挂载上一级的 `/storage`"),
2: ("U","第三期候选（外部程序）","aria2c 需另找静态 arm64 版本，不在 hub 里重写。下载目录 /storage/emulated/0/Download 可写（实测）。关键前提「关机待机时下载不中断」未验证；原文要求的 wifi_sleep_policy 实测已经是 2。","关闭投影仪画面后下载停止……需配合执行模块 11 中的网络防休眠配置（`settings put global wifi_sleep_policy 2`）"),
3: ("U","不纳入","53 端口不能绑定（实测 1024 以下都不行），要靠路由器把 53 转到 5353，很多家用路由器做不到；DNS 分流和去广告已由 Clash 负责。原文说投影仪是「Wi-Fi 6」，USB ID 显示网卡是联发科 MT7663（Wi-Fi 5）。","极米 Z6X Pro 拥有充裕的可用内存（1.5GB）与 Wi-Fi 6 低延迟连接"),
4: ("U","第三期候选","需要电视浏览器同时硬解多路视频，路数没有验证。原文的芯片说法是错的：实际是海思 Hi3751V660、8 核 A55，不是联发科 MT9669、4 核 A73。","极米 Z6X Pro 搭载联发科 MT9669 芯片……通常支持 2~4 路 1080p（或 1 路 4K）同时硬解"),
5: ("C","不纳入 hub（可单独部署）","Navidrome 本身是 Go 静态程序，可以按 Go 服务的方式单独部署；不在 hub 里重写。",None),
6: ("C","hub·control（一期）","按键控制可行（input keyevent 实测可用）。但原文切 HDMI 用的 `xgimi://com.xgimi.home/hdmi` **实测没有任何界面响应**（官方桌面已卸载）；信号源切换要另找办法，备用键值 178 未测。","am start -a android.intent.action.VIEW -d \"xgimi://com.xgimi.home/hdmi\""),
7: ("U","hub 运行前提（已实测：关屏在线、关机睡眠）","wifi_sleep_policy 实测已经是 2。极米电源菜单只有关屏、关机、重启、定时关机，没有「待机」。**关屏已实测**：安卓仍是 Awake、显示 ON，30 分钟内网络和所有端口在线，原文担心的「15 分钟后进入 Doze 断网」没有发生。「关机」也已实测：其实是挂起到内存的睡眠，约 14 秒后断网，开机后进程原样恢复。stay_on_while_plugged_in 实测是 0。","按下遥控器关机后，系统通常在 15 分钟后进入深度睡眠（Doze Mode），切断 Wi-Fi 芯片供电并挂起 CPU"),
8: ("U","第三期候选（files 扩展）","可行但优先级低：缩略图要 CPU，原文要求并发限 2 合理。原文的「4 核 A73」是错的。",None),
9: ("C","hub·files（一期，上传接口）","合并为 files 模块的上传接口：流式落盘、先写 .tmp 再改名，这两条原文的设计是对的。",None),
10: ("C","hub·metrics（一期）","读 /proc 和 /sys 可行（实测）。原文说能读「光机温度」不成立：温度区只有 cpu_thermal 和 vou_thermal。「夜间自愈清理」不需要，不做。","通过直接读取……`/sys/class/thermal/thermal_zone*/temp`（获取光机与核心摄氏度）"),
11: ("C","hub·paste（一期）","可行。input text 只支持 ASCII，原文说对了。但原文说 `am start VIEW` 会「自动调起最佳播放器」——实测视频链接**没有默认播放器**，会弹出选择框。","Android 系统会自动调起内置的最佳播放器（或 VLC）进行硬件解码播放"),
12: ("C","第三期候选（iptv，合并 12/48/59）","可行（纯网络任务）。直播源、节目单三篇合成一个可选模块，优先级低。",None),
13: ("C","第三期候选","可行（纯 Go 解析 zip），优先级低。",None),
14: ("C","hub·speed（一期）","可行。原文说非 root 不能发 ICMP 要调用系统 ping——实测普通身份就能直接发 ICMP（ping_group_range 放开了），不必调用外部命令。原文的「4 核 A73 / MT9669 单核跑满 800Mbps」芯片说法错误。","由于 Linux 限制普通非特权用户创建原始套接字（Raw Socket），探针通过调用系统自带的 `/system/bin/ping` 命令"),
15: ("C","hub·control（一期按键与宏，二期触控板）","按键宏可行。触控板需要注入鼠标事件：/dev/uinput 可写（实测），但系统是否接受虚拟鼠标未验证，放第二期。","在本地调用 Linux shell `input swipe` 或注入鼠标指针事件"),
16: ("U","第二期·dlna","可行性有前提：UDP 1900 已被系统组件占用（实测，uid 1000）；视频链接没有默认播放器，会弹选择框。要先装好播放器并设为默认。",None),
17: ("C","hub·wol（一期）","可行。普通身份 ICMP ping 实测可用；魔术包是普通 UDP 广播。",None),
18: ("U","第二期·notify（先验证）","`cmd notification post` 存在（实测），但电视上能不能显示出来未验证。原文的方案 B（悬浮窗 TYPE_APPLICATION_OVERLAY）需要一个 App，shell 做不到。","方案 B：通过极简的前端 WebView 浮窗（基于 `android.view.WindowManager` 的悬浮窗图层）"),
19: ("D","不可行","shell 不在 audio 组，/dev/snd 不可读写（实测）；系统里没有 tinyplay；AudioTrack 要在 App 里用。shell 进程放不出声音。","Go 服务在本地通过管道调用系统的 `tinyplay` 工具或 Android AudioTrack API 直接写入硬件音频设备节点"),
20: ("C","第二期·webshell","/dev/ptmx 可读写（实测），可行。等于把 shell 权限开放给网页，必须鉴权、默认关闭。",None),
21: ("D","不纳入","1445 端口能绑定，但原文的核心卖点「所有设备打开网络邻居即可直接访问」不成立：Windows 资源管理器只认 445 端口（原文自己在排坑里也承认了）。WebDAV 已覆盖文件共享。","所有设备打开网络邻居即可直接访问"),
22: ("C","不纳入","可行但依赖访问 TMDB（外网），收益低。",None),
23: ("C","第三期候选","可行（1883 是高位端口）。目前没有 MQTT 设备的需求，不做。",None),
24: ("C","不纳入","可行，但 Clash 已在 [::]:7890 监听（实测），局域网设备可以直接用 Clash 的混合端口，不需要再做一个。",None),
25: ("C","不纳入","可行，收益低。",None),
26: ("C","不纳入","可行，但 WebDAV 已覆盖。原文命令里的 IP（192.168.1.100）和路径（/mnt/media_rw）都不对：投影仪是 192.168.0.109，/mnt/media_rw 对 shell 不可访问（实测）。","-dir /mnt/media_rw/USB_DISK/s3_storage"),
27: ("C","不纳入（安全）","可行，但会把服务暴露到公网，与本项目只在局域网使用的原则冲突。",None),
28: ("C","hub·metrics（一期，合并）","与 Go-10 合并：metrics 模块同时提供 JSON 和 Prometheus 文本格式。",None),
29: ("C","hub·core（一期，鉴权）","简化为 core 的 Bearer token 鉴权，不做 JWT 单点登录。",None),
30: ("C","不纳入","可行，收益低。原文端口 9418 是 git 协议端口却跑 HTTP，路径用了不可访问的 /mnt/media_rw。",None),
31: ("C","hub·control（一期，合并）","合并到 control 模块，用简单的 REST 接口代替 JSON-RPC。",None),
32: ("U","不纳入","原文说用 gortsplib 做 MP4/MKV 解复用——gortsplib 是 RTSP 库，不负责 MP4/MKV 解封装，技术选型存疑；收益低。","Go 1.27 + `aler9/gortsplib` 底层流解析"),
33: ("U","不纳入","需要公网可达和证书，与局域网原则冲突。",None),
34: ("C","hub·control（一期，合并）","合并到 control：外部 Webhook 触发预设动作（按键序列、打开应用）。参数用数组传给 exec 不拼字符串，原文这条是对的。",None),
35: ("C","不纳入","可行，但 WebDAV 和 SSH 已覆盖。",None),
36: ("D","不可行","DHCP 要绑定 67 端口（实测 1024 以下不能绑）；原文提的 `setcap` 需要 root。","需通过 Linux 能力集授权 `setcap cap_net_bind_service=+ep`"),
37: ("C","不纳入","可行（实测投影仪有公网 IPv6 地址），但本项目不对公网开放。",None),
38: ("C","不纳入","可行，分流已由 Clash 负责。",None),
39: ("C","不纳入","可行，收益低。",None),
40: ("D","不可行","Miracast 由系统投屏应用通过 Wi-Fi P2P 建立，外部进程插不进信令中间。",None),
41: ("D","不可行","服务端需要音频输入源、客户端需要出声，shell 进程两头都碰不到音频设备。",None),
42: ("C","不纳入","可行，依赖外网字幕站，收益低。",None),
43: ("C","hub·core（一期，简化）","简化为 core 的日志轮转和 `/api/logs`（最近 N 行），不做 Loki 协议。",None),
44: ("U","第三期候选","HomeKit 需要 mDNS：UDP 5353 已被系统 mdnsd（uid 1020）占用（实测），能否共用未验证。",None),
45: ("C","不纳入","可行，但定时外网测速耗流量，收益低。",None),
46: ("C","hub·wol（一期，合并）","合并到 wol 模块。",None),
47: ("C","第三期候选（与 Go-08 一起）","可行，跟相册一起做。",None),
48: ("C","第三期候选（iptv，合并到 Go-12）","合并。",None),
49: ("C","hub·speed（二期，可选）","可行。第一期先做网页测速，iperf3 协议兼容放第二期。",None),
50: ("C","不纳入","可行，但 AList 本身就是 Go 静态程序，可以直接单独部署，不必重写。",None),
51: ("C","不纳入","可行，本项目不对公网开放，用不到证书。",None),
52: ("C","不纳入","可行，收益低。",None),
53: ("C","第二期·lanscan","可行。UDP 1900 已被系统占用（实测），只发 M-SEARCH 收单播回复即可，或用 SO_REUSEADDR。",None),
54: ("C","不纳入","可行，没有传感器数据需求。",None),
55: ("U","第三期候选","tsnet 用户态可行性未验证；如果以后需要外出访问家里，这是首选方案。",None),
56: ("U","不纳入","接收端要在电视上解码显示（得开浏览器页面），浏览器发起屏幕共享还要求 HTTPS；整体复杂、收益低。",None),
57: ("C","tools·hash（一期，只报告）","合并到 z6x-tools 的 hash 子命令，只报告重复、不建硬链接：U 盘常见的 FAT32/exFAT 不支持硬链接（原文排坑里自己也写了）。",None),
58: ("C","hub·core（二期，配置页）","第一期先在首页只读展示配置，第二期再做网页修改。",None),
59: ("C","第三期候选（iptv，合并到 Go-12）","合并。",None),
60: ("C","hub 架构（规格基础）","单进程、配置开关模块、recover 隔离、端口集中规划——这些设计采纳为 z6x-hub 的架构。但原文的配置用了 /mnt/media_rw（不可访问），「CPU 上下文切换降低 70%」「59 项子服务」没有依据。","storage_root: /mnt/media_rw/USB_DISK"),
}
R = {
1: ("D","tools·run（二期，改为进程守护）","前提不成立：原文担心看门狗会被低内存回收杀掉，实测从 ADB 启动的进程 oom 分是 -1000，不会被杀。崩溃重启的功能保留，并入 tools 的 run 子命令。","当电视前台播放 4K 超高清电影……连看门狗本身都会被 Android TV 的 LMK（低内存查杀）机制一同杀死"),
2: ("C","tools·keymap（一期）","可行：shell 在 input 组，遥控器节点可读（实测）。但原文写的遥控器节点 event2 不对：event2 是虚拟键盘 qwerty，遥控器是 event13。","启动 Rust 按键监听服务（绑定蓝牙遥控器 event2）"),
3: ("D","不可行","/dev/snd 不可读写（实测，shell 不在 audio 组）。",None),
4: ("C","tools·hash（一期）","可行。原文「MT9669 的 4 个 Cortex-A73」不对，实际是 8 核 A55（同样有 NEON）。","MediaTek MT9669 的 4 个 Cortex-A73 核心内部均集成了 NEON 向量处理单元"),
5: ("U","不纳入","用户态隧道理论可行，但 Clash 已提供 VPN；/dev/net/tun 对 shell 不可访问（实测）。",None),
6: ("C","不纳入","可行，没有需求。",None),
7: ("D","不可行","内核里没有 hci 蓝牙设备（/sys/class/bluetooth 为空，实测），原始 HCI 套接字无从打开。原文说的网卡型号 MT7921 也不对，USB ID 是 0e8d:7663。","极米 Z6X Pro 配备了 Wi-Fi/BT 组合芯片（MT7921）"),
8: ("D","不纳入","/proc/kmsg 不可读、dmesg 没权限（实测）。只剩 logcat 能读，系统自己就有 crash 缓冲区。","后台通过读取 `/proc/kmsg`（内核日志流）"),
9: ("D","不可行","端口敲门要捕获未开放端口上的包，需要原始套接字 / pcap（没有 CAP_NET_RAW）。",None),
10: ("U","不纳入","53 端口不能绑定；Clash 已加密 DNS。",None),
11: ("C","tools·pack（二期）","可行。原文「4 核 A73」不对。",None),
12: ("C","不纳入","可行；hub 自己保证不写敏感信息即可。",None),
13: ("C","不单独做","hub 需要推送时在 Go 里实现，不再起一个 Rust 进程。",None),
14: ("C","tools·sys（一期）","可行（读 /proc、/sys 实测可用）。",None),
15: ("U","tools·iobench（二期）","块设备不可访问，只能对文件测；FAT/exFAT 是否支持 O_DIRECT 未验证（原文自己也提到会降级）。",None),
16: ("C","不纳入（第三期可作为 files 限速选项）","可行，暂无需求。",None),
17: ("C","合并到 hub·files","与 Go-01 重复，WebDAV 只做一份（Go）。",None),
18: ("C","tools·key（一期）","可行：遥控器节点和 /dev/uinput 对 shell 都可写（实测）。原文说 input keyevent 每次 200~400ms，实测 79~106ms（三次）；仍然慢，值得做。节点 event2 不对，应为 event13。","单次调用耗时长达 200ms ~ 400ms"),
19: ("C","tools·run（二期）","可行，和 Rust-01 合并为一个极简进程守护。",None),
20: ("D","不可行","AF_PACKET 需要 CAP_NET_RAW，shell 没有；原文提的 setcap 需要 root。",None),
21: ("C","不纳入","与 Go-23 重复。原文说「标准 MQTT 端口 1883 需要 root 权限」不对：1883 大于 1024，普通身份可以绑定。","标准 MQTT 端口 1883 需要 root 权限"),
22: ("C","合并到 hub·files","与 Go-01 的下载功能重复。",None),
23: ("D","不可行","目前没有串口设备节点（实测无 /dev/ttyUSB*、/dev/ttyACM*）；原文说的 `chmod 666 /dev/ttyUSB0` 需要 root。","在非 root 的 shell 下启动前需执行 `chmod 666 /dev/ttyUSB0`"),
24: ("D","不可行","/dev/net/tun 对 shell 不可访问（实测）。",None),
25: ("D","不可行","/dev/snd 不可读写（实测）。",None),
26: ("C","不纳入","可行，Clash 已提供混合端口。",None),
27: ("C","不纳入","可行，暂无需求。",None),
28: ("C","不纳入","hub 内部有定时功能即可。",None),
29: ("C","合并到 tools·sys","可行。原文说能读「光机温度」不成立：只有 cpu_thermal、vou_thermal。","追踪 CPU 核心、GPU 以及光学投影模组温度趋势"),
30: ("U","不纳入","没有发送端配合，原文要求的 sysctl 调整需要 root。",None),
31: ("C","tools·watch（一期）","可行。原文说 max_user_watches 是 8192，实测正是 8192；但扩大它的 echo 命令需要 root。",None),
32: ("D","不可行","/dev/graphics/fb0 属于 graphics 组，shell 不在这个组（实测）。截图用 adb exec-out screencap 即可（见「给投影仪截图」）。",None),
33: ("C","不纳入","可行，没有需求。",None),
34: ("C","tools·ping（一期）","可行：普通身份可发 ICMP（实测）。原文建议的 `cmd wifi set-low-latency-mode enabled` 在这台机器上不存在（cmd wifi 帮助里没有）。","实测前应通过 `cmd wifi set-low-latency-mode enabled` 开启低延迟模式"),
35: ("U","第三期候选","UDP 5353 已被系统 mdnsd 占用（实测），能否共存未验证。",None),
36: ("C","tools·iobench（二期）","可行（对文件测）。",None),
37: ("C","第三期候选","/dev/ptmx 可用（实测），可行，优先级低。",None),
38: ("C","合并到 tools·pack","zstd 足够，lz4 不单独做。",None),
39: ("D","不可行","/dev/cec0 不存在（实测）。",None),
40: ("D","不可行","/dev/snd/controlC0 属于 audio 组，shell 不可访问（实测）。",None),
41: ("D","hidg0 部分不可行，uinput 部分合并到 tools·key","/dev/hidg0 不存在（没有 USB gadget）。原文说 /dev/uinput 默认只属于 system 或 root、需要 chmod——实测 /dev/uinput 属于 uhid 组，shell 就在这个组里，可直接读写。","Android 下 `/dev/uinput` 默认可能只属于 `system` 或 `root`，在普通 shell 启动前需通过 `chmod 666 /dev/uinput` 赋予读写权限"),
42: ("U","不纳入","53 端口不能绑定。原文让用 `setprop net.dns1` 引导系统 DNS——安卓 8 以后系统不再使用 net.dns1（实测这个属性为空），这个办法无效。","需在 shell 中通过 `setprop net.dns1 127.0.0.1` 引导系统优先走本地代理"),
43: ("C","合并到 hub·webshell（二期）","与 Go-20 重复，网页终端只做一份（Go）。",None),
44: ("C","不纳入","可行，没有需求。",None),
45: ("D","不可行","内核没有 hci 设备（实测），原始 HCI 套接字打不开。",None),
46: ("C","不纳入","可行，没有使用方。",None),
47: ("C","不纳入","可行，收益低。",None),
48: ("D","不可行","/sys/fs/cgroup 对 shell 不可写（实测）。原文的退路 setpriority（nice）可以，但不值得单独做工具。",None),
49: ("U","改为命令集（见 z6x-tools 规格）","原文把 Rust 做成第二个常驻底座。审核后：Rust 里可行的几乎都是「跑一次给结果」的工具，改为 BusyBox 式命令集；只有按键重映射常驻。原文挑选的五个底座模块里，音频混音、BLE 中继在这台机器上不可行，黑匣子缺内核日志权限。","Rust 专注跑底层硬件（Watchdog、evdev 输入、音频硬件直写、蓝牙原始套接字）"),
}
GROUPS = [
 ("review-files","审核：文件与存储","WebDAV、上传、压缩、哈希、对象存储……", [("G",n) for n in (1,8,9,13,21,26,30,35,47,50,57)] + [("R",n) for n in (4,6,11,15,17,22,27,36,38,47)]),
 ("review-media","审核：下载、影音与直播","离线下载、音乐、视频、投屏、字幕、直播源……", [("G",n) for n in (2,4,5,12,16,19,22,25,32,39,41,42,48,52,56,59)] + [("R",n) for n in (3,25,30,40)]),
 ("review-network","审核：网络、代理与远程访问","DNS、代理、测速、端口映射、穿透、组播……", [("G",n) for n in (3,14,24,27,33,36,37,38,45,46,49,51,53,55)] + [("R",n) for n in (5,9,10,16,20,24,26,34,35,42,46)]),
 ("review-control","审核：遥控、自动化与通知","按键、遥控网页、Webhook、通知、智能家居、蓝牙、串口……", [("G",n) for n in (6,11,15,17,18,23,31,34,40,44,54)] + [("R",n) for n in (2,7,13,18,21,23,39,41,45)]),
 ("review-system","审核：系统、运维与架构","看门狗、监控、日志、终端、隔离、两个聚合架构……", [("G",n) for n in (7,10,20,28,29,43,58,60)] + [("R",n) for n in (1,8,12,14,19,28,29,31,32,33,37,43,44,48,49)]),
]
